sudo: required

services:
  - docker

before-install:
  - docker login -u 'ronny9313' -p 'Smyths@123' 
  - docker build -t ronny9313/docker-react -f Dockerfile.dev .

script:
  - docker run ronny9313/docker-react npm run test -- --coverage