sudo: required

travis encrypt DOCKER_USER=ronny9313 --add
travis encrypt DOCKER_PASS=Smyths@123 --add

services:
  - docker

before-install:
  - docker build -t ronny9313/docker-react -f Dockerfile.dev .

script:
  - docker run ronny9313/docker-react npm run test -- --coverage