sudo: required

services:
  - docker

before_install:
- docker build -t ronny9313/docker-react -f Dockerfile.dev .

script:
  - docker run ronny9313/docker-react npm run test -- --coverage
  - docker ps -a